"""Smoke test an idle local Compose service; cleans only jobs generated by this run.

python deploy/validate_docker.py          # service without GPU passthrough
python deploy/validate_docker.py --gpu    # service with compose.nvidia.yaml
"""
import argparse
import base64
import hashlib
import io
import json
import os
import subprocess
import time
import uuid
import zipfile
from urllib.error import HTTPError
from urllib.request import Request, urlopen


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--gpu", action="store_true")
    parser.add_argument("--url", default="http://127.0.0.1:8899")
    parser.add_argument("--container", help="Use docker exec for a separate test container")
    args = parser.parse_args()
    password = os.getenv("VIDEO_PROCESSOR_AUTH_PASSWORD", "")
    username = os.getenv("VIDEO_PROCESSOR_AUTH_USER", "admin")
    auth_headers = {}
    if password:
        credentials = base64.b64encode(f"{username}:{password}".encode()).decode()
        auth_headers["Authorization"] = "Basic " + credentials
    jobs = []
    source_path = f"/tmp/video-processor-smoke-{uuid.uuid4().hex}.mp4"

    def request(path, data=None, method=None, headers=None):
        with urlopen(Request(args.url.rstrip("/") + path, data=data, method=method,
                             headers={**auth_headers, **(headers or {})}), timeout=20) as response:
            return response.read()

    def payload(path, **kwargs):
        return json.loads(request(path, **kwargs))

    def command(*parts):
        prefix = ["docker", "exec", args.container] if args.container else ["docker", "compose", "exec", "-T", "video-processor"]
        return subprocess.check_output([*prefix, *parts])

    def multipart(fields, video=None):
        boundary = "VideoProcessorSmokeBoundary"
        body = bytearray()
        for name, value in fields.items():
            body.extend(f'--{boundary}\r\nContent-Disposition: form-data; name="{name}"\r\n\r\n{value}\r\n'.encode())
        if video is not None:
            for filename, content in ([("smoke.mp4", video)] if isinstance(video, bytes) else video):
                body.extend(f'--{boundary}\r\nContent-Disposition: form-data; name="videos"; filename="{filename}"\r\nContent-Type: video/mp4\r\n\r\n'.encode())
                body.extend(content)
                body.extend(b"\r\n")
        body.extend(f"--{boundary}--\r\n".encode())
        return bytes(body), {"Content-Type": "multipart/form-data; boundary=" + boundary}

    def finished(job_id):
        jobs.append(job_id)
        for _ in range(120):
            detail = payload('/api/jobs/' + job_id)
            if detail['job']['status'] in ('done', 'error'):
                break
            time.sleep(.5)
        assert detail['job']['status'] == 'done', detail
        assert detail['job']['worker_count'] == 0, detail
        return detail

    def verify(job_id, fmt, expected_device):
        detail = finished(job_id)
        file = detail['files'][0]
        assert file['encoder_device'] == expected_device, file
        assert file['output_exists'], file
        expected_encoder = ('hevc_nvenc' if fmt == 'h265' else 'h264_nvenc') if expected_device == 'nvidia' else ('libx265' if fmt == 'h265' else 'libx264')
        assert file['encoder_name'] == expected_encoder, file
        settings = json.loads(detail['job']['settings_json'])
        assert settings['crf'] == 28 and settings['gpu_quality'] == 25
        assert settings['gpu_concurrency'] == config['gpu_max_concurrent']
        assert settings['gpu_concurrency_mode'] == 'auto' and settings['gpu_target_percent'] == 80
        content = request(f"/api/jobs/{job_id}/files/{file['id']}/download")
        assert len(content) > 100
        probe = json.loads(command('ffprobe', '-v', 'error', '-of', 'json', '-show_streams', file['output_path']))
        assert any(s['codec_type'] == 'audio' for s in probe['streams'])
        assert any(s.get('codec_name') == ('hevc' if fmt == 'h265' else 'h264') for s in probe['streams'])
        payload(f'/api/jobs/{job_id}/archive', data=b'', method='POST')
        for _ in range(60):
            state = payload(f'/api/jobs/{job_id}/archive')
            if state['status'] in ('ready', 'error'):
                break
            time.sleep(.2)
        assert state['status'] == 'ready', state
        assert request(f'/api/jobs/{job_id}/download-all').startswith(b'PK')
        print(f'PASS: {fmt}/{expected_device}, watermarks, audio, download, archive, independent quality values', flush=True)
        return file, hashlib.sha256(content).hexdigest()

    config = payload('/api/config')
    assert config['gpu']['available'] == args.gpu, config['gpu']
    assert config['gpu_concurrency_mode'] == 'auto' and config['gpu_target_percent'] == 80
    assert payload('/health')['ok']
    assert payload('/api/current-job')['job'] is None, 'Run smoke tests while the service is idle'
    try:
        command('ffmpeg', '-v', 'error', '-y', '-f', 'lavfi', '-i', 'testsrc2=size=320x240:rate=15',
                '-f', 'lavfi', '-i', 'sine=frequency=440', '-t', '2', '-c:v', 'libx264', '-c:a', 'aac', source_path)
        source = command('cat', source_path)
        modes = [('auto', 'h264'), ('nvidia' if args.gpu else 'auto', 'h265'),
                 ('nvidia' if args.gpu else 'auto', 'mkv'), ('cpu', 'h264')]
        fields = dict(crf='28', gpu_quality='25', gpu_preset='p4', gpu_concurrency='99')
        for mode, fmt in modes:
            fields.update(encoder_device=mode, format_type=fmt)
            body, headers = multipart(fields, source)
            job_id = payload('/api/jobs', data=body, headers=headers)['id']
            file, _ = verify(job_id, fmt, 'nvidia' if args.gpu and mode != 'cpu' else 'cpu')
            if not args.gpu and mode == 'auto':
                assert file['fallback_reason']
        session = payload('/api/uploads/init', data=json.dumps({'files': [{'path': 'smoke.mp4', 'size': len(source)}]}).encode(), headers={'Content-Type': 'application/json'})
        session_id = session['id']
        payload(f'/api/uploads/{session_id}/chunks/0/0', data=source, method='PUT')
        if not args.gpu:
            fields.update(encoder_device='nvidia', format_type='h264')
            body, headers = multipart(fields)
            try:
                request(f'/api/uploads/{session_id}/complete', data=body, headers=headers)
                raise AssertionError('Strict NVIDIA mode must reject unavailable GPU')
            except HTTPError as error:
                assert error.code == 400
        fields.update(encoder_device='auto', format_type='h265')
        body, headers = multipart(fields)
        estimate_path = f'/api/uploads/{session_id}/estimate'
        estimate = payload(estimate_path, data=body, headers=headers)
        for _ in range(120):
            if estimate['status'] not in ('running', 'canceling'):
                break
            time.sleep(.25)
            estimate = payload(estimate_path)
        assert estimate['status'] == 'done', estimate
        assert estimate['files'][0]['full_trial'], estimate
        assert estimate['files'][0]['encoder_device'] == ('nvidia' if args.gpu else 'cpu'), estimate
        cached = payload(estimate_path, data=body, headers=headers)
        assert cached['id'] == estimate['id'] and cached['status'] == 'done', cached
        assert payload('/api/current-job')['job'] is None, 'Estimation must not create a processing job'
        job_id = payload(f'/api/uploads/{session_id}/complete', data=body, headers=headers)['id']
        file, _ = verify(job_id, 'h265', 'nvidia' if args.gpu else 'cpu')
        output_size = int(command('stat', '-c', '%s', file['output_path']))
        assert estimate['totals']['min_bytes'] <= output_size <= estimate['totals']['max_bytes'], (estimate, output_size)
        print('PASS: size estimation includes audio/watermarks, caches matching parameters, and reuses uploads for actual encoding', flush=True)
        print('PASS: resumable upload preserves GPU parameters; strict GPU rejection does not lock the upload session', flush=True)

        command('ffmpeg', '-v', 'error', '-y', '-f', 'lavfi', '-i', 'color=c=red:size=320x240:rate=15',
                '-t', '2', '-c:v', 'libx264', source_path + '-other.mp4')
        other = command('cat', source_path + '-other.mp4')
        fields.update(encoder_device='auto', format_type='h264')
        body, headers = multipart(fields, [('clip.mp4', source), ('clip.mov', other)])
        detail = finished(payload('/api/jobs', data=body, headers=headers)['id'])
        assert len(detail['files']) == 2
        assert len({file['output_path'] for file in detail['files']}) == 2, detail
        hashes = {hashlib.sha256(request(f"/api/jobs/{detail['job']['id']}/files/{file['id']}/download")).hexdigest()
                  for file in detail['files']}
        assert len(hashes) == 2, 'Different source videos must retain different outputs'
        print('PASS: same-stem MP4/MOV uploads produce two distinct, downloadable outputs', flush=True)

        command('ffmpeg', '-v', 'error', '-y', '-stream_loop', '29', '-i', source_path,
                '-c', 'copy', source_path + '-long.mp4')
        long_video = command('cat', source_path + '-long.mp4')
        fields.update(encoder_device='cpu', format_type='h264', encoder_preset='slow')
        body, headers = multipart(fields, long_video)
        job_id = payload('/api/jobs', data=body, headers=headers)['id']
        jobs.append(job_id)
        for _ in range(100):
            detail = payload('/api/jobs/' + job_id)
            if any(file['status'] == 'running' for file in detail['files']):
                break
            assert detail['job']['status'] != 'error', detail
            time.sleep(.1)
        assert any(file['status'] == 'running' for file in detail['files']), detail
        assert payload('/api/jobs/' + job_id + '/pause', data=b'', method='POST')['status'] == 'paused'
        assert payload('/api/jobs/' + job_id + '/resume', data=b'', method='POST')['status'] == 'queued'
        detail = finished(job_id)
        file = detail['files'][0]
        assert file['attempts'] >= 2 and file['output_exists'], detail
        probe = json.loads(command('ffprobe', '-v', 'error', '-of', 'json', '-show_format', file['output_path']))
        assert float(probe['format']['duration']) > 55, probe
        print('PASS: immediate pause/resume stops the old encoder and produces a complete 60-second output', flush=True)
    finally:
        for job_id in dict.fromkeys(jobs):
            payload('/api/jobs/' + job_id, method='DELETE')
        command('rm', '-f', source_path, source_path + '-other.mp4', source_path + '-long.mp4')


if __name__ == '__main__':
    main()
